# Generated by Django 4.0.5 on 2022-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0015_work2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='len',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='prise',
            field=models.FloatField(null=True),
        ),
    ]
