# Generated by Django 4.0.5 on 2022-08-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0016_alter_calc_count_manager_proc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа автомат', 'verbose_name_plural': 'Работы автомат'},
        ),
        migrations.AlterModelOptions(
            name='work2',
            options={'verbose_name': 'Работа ручная', 'verbose_name_plural': 'Работы ручная'},
        ),
    ]
