# Generated by Django 4.0.5 on 2022-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0016_alter_material_len_alter_material_prise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc_count',
            name='manager_proc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calc_count',
            name='margin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calc_count',
            name='not_production',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='calc_count',
            name='reject',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Content',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Lid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Scotch',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Tray',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dm2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work2',
            name='Count',
            field=models.FloatField(null=True),
        ),
    ]
