# Generated by Django 4.1.1 on 2023-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cub_box_0', '0019_pressfoil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('preparation', models.IntegerField(default=0)),
                ('push', models.IntegerField(default=0)),
            ],
        ),
    ]
